/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadCrumb: typeof import('./src/components/AppBreadCrumb.vue')['default']
    AppFooter: typeof import('./src/layouts/AppFooter.vue')['default']
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    AppMenu: typeof import('./src/layouts/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/layouts/AppMenuItem.vue')['default']
    AppProfileDropdown: typeof import('./src/layouts/AppProfileDropdown.vue')['default']
    AppSidebar: typeof import('./src/layouts/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/layouts/AppTopbar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    CategoryForm: typeof import('./src/components/forms/CategoryForm.vue')['default']
    CategoryListItem: typeof import('./src/components/category/CategoryListItem.vue')['default']
    CategorySection: typeof import('./src/components/category/CategorySection.vue')['default']
    CategorySelect: typeof import('./src/components/forms/CategorySelect.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckBox: typeof import('primevue/checkbox')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/forms/LoginForm.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Popover: typeof import('primevue/popover')['default']
    PopOver: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowSelect: typeof import('./src/components/base/RowSelect.vue')['default']
    Select: typeof import('primevue/select')['default']
    TransactionForm: typeof import('./src/components/forms/TransactionForm.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
