export const icons = [
  { label: 'Wallet', value: 'pi pi-wallet' },
  { label: 'Shopping', value: 'pi pi-shopping-bag' },
  { label: 'Home', value: 'pi pi-home' },
  { label: 'Gift', value: 'pi pi-gift' },
  { label: 'Apple', value: 'pi pi-apple' },
  { label: 'Star', value: 'pi pi-star' },
  { label: 'Car', value: 'pi pi-car' },
  { label: 'Credit Card', value: 'pi pi-credit-card' },
  { label: 'Briefcase', value: 'pi pi-briefcase' },
  { label: 'Money Bill', value: 'pi pi-money-bill' },
  { label: 'Chart', value: 'pi pi-chart-line' },
  { label: 'Bank', value: 'pi pi-building' },
  { label: 'Bolt', value: 'pi pi-bolt' },
  { label: 'Water', value: 'pi pi-sliders-h' },
  { label: 'Phone', value: 'pi pi-phone' },
  { label: 'Internet', value: 'pi pi-globe' },
  { label: 'Bus', value: 'pi pi-directions' },
  { label: 'Plane', value: 'pi pi-send' },
  { label: 'Taxi', value: 'pi pi-compass' },
  { label: 'Cutlery', value: 'pi pi-bars' }, 
  { label: 'Plus', value: 'pi pi-plus' },
  { label: 'Ellipsis', value: 'pi pi-ellipsis-h' },
  { label: 'Question', value: 'pi pi-question' },
]
